version: '3'
services:
  go-app:
    build: ./go-app
    ports:
      - "8080:8080"
  nextjs-app:
    build: ./nextjs-app
    ports:
      - "3000:3000"
  wordpress-app:
    build: ./wordpress-app
    ports:
      - "8000:80"